### ISSUE TITLE
Determination of primary constructor is incorrect

### ISSUE THREAD

**Issue by jacobg** [applctv/gcp-scala-datastore#38]
In `ReflectionHelper`, there's a couple places where it tries to figure out the primary constructor (i.e., default case class constructor), such as in `instanceToDatastoreEntity`. It assumes that the primary constructor is the first in the list returned by `class.getConstructors`. However, that is not a correct assumption. The order is non-deterministic and can change each time the application is run:

https://stackoverflow.com/questions/34289801/how-is-the-order-of-the-array-what-class-getconstructors-returns-in-java

An example case class might look like this:
```
case class Foo(id: Long, bar: String) extends BaseEntity {
   def this(baz: Baz) = this (baz.id, baz.bar)
}
```

The result is that if it chooses a non-primary constructor then the annotates dictionary may not be populated, and it will throw an exception:
```
key not found: 0
java.util.NoSuchElementException: key not found: 0
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:101)
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:99)
	at io.applicative.datastore.util.reflection.ReflectionHelper.$anonfun$instanceToDatastoreEntity$3(ReflectionHelper.scala:63)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at io.applicative.datastore.util.reflection.ReflectionHelper.instanceToDatastoreEntity(ReflectionHelper.scala:61)
	at io.applicative.datastore.util.reflection.ReflectionHelper.instanceToDatastoreEntity$(ReflectionHelper.scala:44)
	at io.applicative.datastore.DatastoreService$.instanceToDatastoreEntity(DatastoreService.scala:14)
	at io.applicative.datastore.DatastoreService$.$anonfun$add$1(DatastoreService.scala:48)
```

Here is a possible solution:
https://stackoverflow.com/questions/16496411/using-the-new-reflection-api-how-to-find-the-primary-constructor-of-a-class

**Comment by jacobg** [comment]
A workaround for now is to use the companion object to define alternative constructors:
```
case class Foo(id: Long, bar: String) extends BaseEntity
object Foo {
  def apply(baz: Baz): Foo = Foo (baz.id, baz.bar)
}
```
